"""Movie and Actro models updated

Revision ID: dfae5f9ddb9f
Revises: b8df63a5e4de
Create Date: 2021-05-25 10:48:19.416173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfae5f9ddb9f'
down_revision = 'b8df63a5e4de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('actor', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('actor', sa.Column('name', sa.String(), nullable=True))
    op.add_column('movie', sa.Column('releaseDate', sa.DateTime(), nullable=True))
    op.add_column('movie', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'title')
    op.drop_column('movie', 'releaseDate')
    op.drop_column('actor', 'name')
    op.drop_column('actor', 'gender')
    op.drop_column('actor', 'age')
    # ### end Alembic commands ###
